import {SECONDS_PER_DAY, SECONDS_PER_MINUTE, SECONDS_PER_HOUR} from '../../../util/constants'

export const GAP_WIDTHS = [0, 1, 8, SECONDS_PER_MINUTE, SECONDS_PER_MINUTE * 8,
  SECONDS_PER_HOUR, SECONDS_PER_HOUR * 8, SECONDS_PER_DAY]

export enum TIMEDISPLAYSIZE {
  TICKS,
  SHORT,
  MEDIUM,
  LONG
}
