export const SECONDS_PER_MINUTE = 60
export const SECONDS_PER_HOUR = 60 * 60
export const SECONDS_PER_DAY = 60 * 60 * 24
export const MSECONDS_PER_SECOND = 1000
export const MSECONDS_PER_MINUTE = SECONDS_PER_MINUTE * MSECONDS_PER_SECOND
export const MSECONDS_PER_HOUR   = SECONDS_PER_HOUR * MSECONDS_PER_SECOND
export const MSECONDS_PER_DAY    = SECONDS_PER_DAY * MSECONDS_PER_SECOND
export const BASE_URL = "http://192.168.91.32:9091"

export enum TIMESCALE {
  YEARS,
  MONTHS,
  DAYS,
  HOURS,
  MINUTES,
  SECONDS,
  FRAMES
}
