/**
 * This file was generated by running this command:
 * ts-node tools\generators\generateSerenityResources.ts
 * on 8/29/2017, 1:28:00 PM
 * from serenity/latex/tex/situations.tex (branch master, commit 29f1886)
 * (if modified by hand, replace this line with modification description)
 */
import { defineMessages } from 'react-intl'

export default defineMessages({
  admin_certExpired: {
    id: 'vxweb.Situations.admin_certExpired',
    defaultMessage: 'Cert Expired',
  },
  admin_certModified: {
    id: 'vxweb.Situations.admin_certModified',
    defaultMessage: 'Cert Modified',
  },
  admin_clipsRemoved: {
    id: 'vxweb.Situations.admin_clipsRemoved',
    defaultMessage: 'Clips Removed',
  },
  admin_coreDbBackupFailed: {
    id: 'vxweb.Situations.admin_coreDbBackupFailed',
    defaultMessage: 'Core Db Backup Failed',
  },
  admin_coreDbBackupHalted: {
    id: 'vxweb.Situations.admin_coreDbBackupHalted',
    defaultMessage: 'Core Db Backup Halted',
  },
  admin_coreDbBackupRemoved: {
    id: 'vxweb.Situations.admin_coreDbBackupRemoved',
    defaultMessage: 'Core Db Backup Removed',
  },
  admin_coreDbBackupRestore: {
    id: 'vxweb.Situations.admin_coreDbBackupRestore',
    defaultMessage: 'Core Db Backup Restore',
  },
  admin_coreDbBackupStarted: {
    id: 'vxweb.Situations.admin_coreDbBackupStarted',
    defaultMessage: 'Core Db Backup Started',
  },
  admin_coreDbBackupSuccess: {
    id: 'vxweb.Situations.admin_coreDbBackupSuccess',
    defaultMessage: 'Core Db Backup Success',
  },
  admin_dataSourceModified: {
    id: 'vxweb.Situations.admin_dataSourceModified',
    defaultMessage: 'Data Source Modified',
  },
  admin_dataStorageModified: {
    id: 'vxweb.Situations.admin_dataStorageModified',
    defaultMessage: 'Data Storage Modified',
  },
  admin_deviceAdded: {
    id: 'vxweb.Situations.admin_deviceAdded',
    defaultMessage: 'Device Added',
  },
  admin_deviceAssigned: {
    id: 'vxweb.Situations.admin_deviceAssigned',
    defaultMessage: 'Device Assigned',
  },
  admin_deviceCommissioned: {
    id: 'vxweb.Situations.admin_deviceCommissioned',
    defaultMessage: 'Device Commissioned',
  },
  admin_deviceDecommissioned: {
    id: 'vxweb.Situations.admin_deviceDecommissioned',
    defaultMessage: 'Device Decommissioned',
  },
  admin_deviceModified: {
    id: 'vxweb.Situations.admin_deviceModified',
    defaultMessage: 'Device Modified',
  },
  admin_deviceRebooted: {
    id: 'vxweb.Situations.admin_deviceRebooted',
    defaultMessage: 'Device Rebooted',
  },
  admin_deviceRemoved: {
    id: 'vxweb.Situations.admin_deviceRemoved',
    defaultMessage: 'Device Removed',
  },
  admin_deviceReset: {
    id: 'vxweb.Situations.admin_deviceReset',
    defaultMessage: 'Device Reset',
  },
  admin_deviceUnassigned: {
    id: 'vxweb.Situations.admin_deviceUnassigned',
    defaultMessage: 'Device Unassigned',
  },
  admin_drawingAdded: {
    id: 'vxweb.Situations.admin_drawingAdded',
    defaultMessage: 'Drawing Added',
  },
  admin_drawingImageRetrieved: {
    id: 'vxweb.Situations.admin_drawingImageRetrieved',
    defaultMessage: 'Drawing Image Retrieved',
  },
  admin_drawingImageModified: {
    id: 'vxweb.Situations.admin_drawingImageModified',
    defaultMessage: 'Drawing Image Modified',
  },
  admin_drawingImageRemoved: {
    id: 'vxweb.Situations.admin_drawingImageRemoved',
    defaultMessage: 'Drawing Image Removed',
  },
  admin_drawingMarkerAdded: {
    id: 'vxweb.Situations.admin_drawingMarkerAdded',
    defaultMessage: 'Drawing Marker Added',
  },
  admin_drawingMarkerModified: {
    id: 'vxweb.Situations.admin_drawingMarkerModified',
    defaultMessage: 'Drawing Marker Modified',
  },
  admin_drawingMarkerRemoved: {
    id: 'vxweb.Situations.admin_drawingMarkerRemoved',
    defaultMessage: 'Drawing Marker Removed',
  },
  admin_drawingModified: {
    id: 'vxweb.Situations.admin_drawingModified',
    defaultMessage: 'Drawing Modified',
  },
  admin_drawingRemoved: {
    id: 'vxweb.Situations.admin_drawingRemoved',
    defaultMessage: 'Drawing Removed',
  },
  admin_drawingsModified: {
    id: 'vxweb.Situations.admin_drawingsModified',
    defaultMessage: 'Drawings Modified',
  },
  admin_exportPathModified: {
    id: 'vxweb.Situations.admin_exportPathModified',
    defaultMessage: 'Export Path Modified',
  },
  admin_licenseAdded: {
    id: 'vxweb.Situations.admin_licenseAdded',
    defaultMessage: 'License Added',
  },
  admin_licenseExpired: {
    id: 'vxweb.Situations.admin_licenseExpired',
    defaultMessage: 'License Expired',
  },
  admin_licenseFailure: {
    id: 'vxweb.Situations.admin_licenseFailure',
    defaultMessage: 'License Failure',
  },
  admin_logAdded: {
    id: 'vxweb.Situations.admin_logAdded',
    defaultMessage: 'Log Added',
  },
  admin_logDownloaded: {
    id: 'vxweb.Situations.admin_logDownloaded',
    defaultMessage: 'Log Downloaded',
  },
  admin_logRemoved: {
    id: 'vxweb.Situations.admin_logRemoved',
    defaultMessage: 'Log Removed',
  },
  admin_memberAdded: {
    id: 'vxweb.Situations.admin_memberAdded',
    defaultMessage: 'Member Added',
  },
  admin_memberModified: {
    id: 'vxweb.Situations.admin_memberModified',
    defaultMessage: 'Member Modified',
  },
  admin_memberRemoved: {
    id: 'vxweb.Situations.admin_memberRemoved',
    defaultMessage: 'Member Removed',
  },
  admin_monitorAdded: {
    id: 'vxweb.Situations.admin_monitorAdded',
    defaultMessage: 'Monitor Added',
  },
  admin_monitorCellModified: {
    id: 'vxweb.Situations.admin_monitorCellModified',
    defaultMessage: 'Monitor Cell Modified',
  },
  admin_monitorModified: {
    id: 'vxweb.Situations.admin_monitorModified',
    defaultMessage: 'Monitor Modified',
  },
  admin_monitorRemoved: {
    id: 'vxweb.Situations.admin_monitorRemoved',
    defaultMessage: 'Monitor Removed',
  },
  admin_monitorwallAdded: {
    id: 'vxweb.Situations.admin_monitorwallAdded',
    defaultMessage: 'Monitorwall Added',
  },
  admin_monitorwallModified: {
    id: 'vxweb.Situations.admin_monitorwallModified',
    defaultMessage: 'Monitorwall Modified',
  },
  admin_monitorwallRemoved: {
    id: 'vxweb.Situations.admin_monitorwallRemoved',
    defaultMessage: 'Monitorwall Removed',
  },
  admin_newExportKeys: {
    id: 'vxweb.Situations.admin_newExportKeys',
    defaultMessage: 'New Export Keys',
  },
  admin_notificationAdded: {
    id: 'vxweb.Situations.admin_notificationAdded',
    defaultMessage: 'Notification Added',
  },
  admin_notificationAddedRole: {
    id: 'vxweb.Situations.admin_notificationAddedRole',
    defaultMessage: 'Notification Added Role',
  },
  admin_notificationRemoved: {
    id: 'vxweb.Situations.admin_notificationRemoved',
    defaultMessage: 'Notification Removed',
  },
  admin_notificationRemovedRole: {
    id: 'vxweb.Situations.admin_notificationRemovedRole',
    defaultMessage: 'Notification Removed Role',
  },
  admin_privilegeAdded: {
    id: 'vxweb.Situations.admin_privilegeAdded',
    defaultMessage: 'Privilege Added',
  },
  admin_privilegeModified: {
    id: 'vxweb.Situations.admin_privilegeModified',
    defaultMessage: 'Privilege Modified',
  },
  admin_privilegeRemoved: {
    id: 'vxweb.Situations.admin_privilegeRemoved',
    defaultMessage: 'Privilege Removed',
  },
  admin_ptzPresetAdded: {
    id: 'vxweb.Situations.admin_ptzPresetAdded',
    defaultMessage: 'Ptz Preset Added',
  },
  admin_ptzPresetRemoved: {
    id: 'vxweb.Situations.admin_ptzPresetRemoved',
    defaultMessage: 'Ptz Preset Removed',
  },
  admin_roleAdded: {
    id: 'vxweb.Situations.admin_roleAdded',
    defaultMessage: 'Role Added',
  },
  admin_roleModified: {
    id: 'vxweb.Situations.admin_roleModified',
    defaultMessage: 'Role Modified',
  },
  admin_roleRemoved: {
    id: 'vxweb.Situations.admin_roleRemoved',
    defaultMessage: 'Role Removed',
  },
  admin_ruleAdded: {
    id: 'vxweb.Situations.admin_ruleAdded',
    defaultMessage: 'Rule Added',
  },
  admin_ruleModified: {
    id: 'vxweb.Situations.admin_ruleModified',
    defaultMessage: 'Rule Modified',
  },
  admin_ruleRemoved: {
    id: 'vxweb.Situations.admin_ruleRemoved',
    defaultMessage: 'Rule Removed',
  },
  admin_scheduleAdded: {
    id: 'vxweb.Situations.admin_scheduleAdded',
    defaultMessage: 'Schedule Added',
  },
  admin_scheduleModified: {
    id: 'vxweb.Situations.admin_scheduleModified',
    defaultMessage: 'Schedule Modified',
  },
  admin_scheduleRemoved: {
    id: 'vxweb.Situations.admin_scheduleRemoved',
    defaultMessage: 'Schedule Removed',
  },
  admin_situationAdded: {
    id: 'vxweb.Situations.admin_situationAdded',
    defaultMessage: 'Situation Added',
  },
  admin_situationModified: {
    id: 'vxweb.Situations.admin_situationModified',
    defaultMessage: 'Situation Modified',
  },
  admin_situationNotificationAdded: {
    id: 'vxweb.Situations.admin_situationNotificationAdded',
    defaultMessage: 'Situation Notification Added',
  },
  admin_situationNotificationRemoved: {
    id: 'vxweb.Situations.admin_situationNotificationRemoved',
    defaultMessage: 'Situation Notification Removed',
  },
  admin_situationRemoved: {
    id: 'vxweb.Situations.admin_situationRemoved',
    defaultMessage: 'Situation Removed',
  },
  admin_sshEnabled: {
    id: 'vxweb.Situations.admin_sshEnabled',
    defaultMessage: 'Ssh Enabled',
  },
  admin_sshDisabled: {
    id: 'vxweb.Situations.admin_sshDisabled',
    defaultMessage: 'Ssh Disabled',
  },
  admin_timetableAdded: {
    id: 'vxweb.Situations.admin_timetableAdded',
    defaultMessage: 'Timetable Added',
  },
  admin_timetableModified: {
    id: 'vxweb.Situations.admin_timetableModified',
    defaultMessage: 'Timetable Modified',
  },
  admin_timetableRemoved: {
    id: 'vxweb.Situations.admin_timetableRemoved',
    defaultMessage: 'Timetable Removed',
  },
  admin_userAdded: {
    id: 'vxweb.Situations.admin_userAdded',
    defaultMessage: 'User Added',
  },
  admin_userModified: {
    id: 'vxweb.Situations.admin_userModified',
    defaultMessage: 'User Modified',
  },
  admin_userNewPassword: {
    id: 'vxweb.Situations.admin_userNewPassword',
    defaultMessage: 'User New Password',
  },
  admin_userRemoved: {
    id: 'vxweb.Situations.admin_userRemoved',
    defaultMessage: 'User Removed',
  },
  admin_userRoleAdded: {
    id: 'vxweb.Situations.admin_userRoleAdded',
    defaultMessage: 'User Role Added',
  },
  admin_userRoleRemoved: {
    id: 'vxweb.Situations.admin_userRoleRemoved',
    defaultMessage: 'User Role Removed',
  },
  admin_vxsDbRebuild: {
    id: 'vxweb.Situations.admin_vxsDbRebuild',
    defaultMessage: 'Vxs Db Rebuild',
  },
  admin_vxsDbRestore: {
    id: 'vxweb.Situations.admin_vxsDbRestore',
    defaultMessage: 'Vxs Db Restore',
  },
  admin_vxsReconfigured: {
    id: 'vxweb.Situations.admin_vxsReconfigured',
    defaultMessage: 'Vxs Reconfigured',
  },
  analytic_abandonedObject: {
    id: 'vxweb.Situations.analytic_abandonedObject',
    defaultMessage: 'Abandoned Object',
  },
  analytic_noAbandonedObject: {
    id: 'vxweb.Situations.analytic_noAbandonedObject',
    defaultMessage: 'No Abandoned Object',
  },
  analytic_adaptiveMotion: {
    id: 'vxweb.Situations.analytic_adaptiveMotion',
    defaultMessage: 'Adaptive Motion',
  },
  analytic_noAdaptiveMotion: {
    id: 'vxweb.Situations.analytic_noAdaptiveMotion',
    defaultMessage: 'No Adaptive Motion',
  },
  analytic_directionalMotion: {
    id: 'vxweb.Situations.analytic_directionalMotion',
    defaultMessage: 'Directional Motion',
  },
  analytic_noDirectionalMotion: {
    id: 'vxweb.Situations.analytic_noDirectionalMotion',
    defaultMessage: 'No Directional Motion',
  },
  analytic_loitering: {
    id: 'vxweb.Situations.analytic_loitering',
    defaultMessage: 'Loitering',
  },
  analytic_noLoitering: {
    id: 'vxweb.Situations.analytic_noLoitering',
    defaultMessage: 'No Loitering',
  },
  analytic_motion: {
    id: 'vxweb.Situations.analytic_motion',
    defaultMessage: 'Motion',
  },
  analytic_noMotion: {
    id: 'vxweb.Situations.analytic_noMotion',
    defaultMessage: 'No Motion',
  },
  analytic_objectCount: {
    id: 'vxweb.Situations.analytic_objectCount',
    defaultMessage: 'Object Count',
  },
  analytic_noObjectCount: {
    id: 'vxweb.Situations.analytic_noObjectCount',
    defaultMessage: 'No Object Count',
  },
  analytic_objectRemoval: {
    id: 'vxweb.Situations.analytic_objectRemoval',
    defaultMessage: 'Object Removal',
  },
  analytic_noObjectRemoval: {
    id: 'vxweb.Situations.analytic_noObjectRemoval',
    defaultMessage: 'No Object Removal',
  },
  analytic_sabotage: {
    id: 'vxweb.Situations.analytic_sabotage',
    defaultMessage: 'Sabotage',
  },
  analytic_noSabotage: {
    id: 'vxweb.Situations.analytic_noSabotage',
    defaultMessage: 'No Sabotage',
  },
  analytic_stoppedVehicle: {
    id: 'vxweb.Situations.analytic_stoppedVehicle',
    defaultMessage: 'Stopped Vehicle',
  },
  analytic_noStoppedVehicle: {
    id: 'vxweb.Situations.analytic_noStoppedVehicle',
    defaultMessage: 'No Stopped Vehicle',
  },
  client_logoff: {
    id: 'vxweb.Situations.client_logoff',
    defaultMessage: 'Logoff',
  },
  client_logon: {
    id: 'vxweb.Situations.client_logon',
    defaultMessage: 'Logon',
  },
  client_savedViewAccepted: {
    id: 'vxweb.Situations.client_savedViewAccepted',
    defaultMessage: 'Saved View Accepted',
  },
  client_savedViewReceived: {
    id: 'vxweb.Situations.client_savedViewReceived',
    defaultMessage: 'Saved View Received',
  },
  client_savedViewSent: {
    id: 'vxweb.Situations.client_savedViewSent',
    defaultMessage: 'Saved View Sent',
  },
  client_snooze: {
    id: 'vxweb.Situations.client_snooze',
    defaultMessage: 'Snooze',
  },
  client_tabAdded: {
    id: 'vxweb.Situations.client_tabAdded',
    defaultMessage: 'Tab Added',
  },
  client_tabModified: {
    id: 'vxweb.Situations.client_tabModified',
    defaultMessage: 'Tab Modified',
  },
  client_tabRemoved: {
    id: 'vxweb.Situations.client_tabRemoved',
    defaultMessage: 'Tab Removed',
  },
  client_workspaceAdded: {
    id: 'vxweb.Situations.client_workspaceAdded',
    defaultMessage: 'Workspace Added',
  },
  client_workspaceModified: {
    id: 'vxweb.Situations.client_workspaceModified',
    defaultMessage: 'Workspace Modified',
  },
  client_workspaceRemoved: {
    id: 'vxweb.Situations.client_workspaceRemoved',
    defaultMessage: 'Workspace Removed',
  },
  hardware_cpuLoad: {
    id: 'vxweb.Situations.hardware_cpuLoad',
    defaultMessage: 'Cpu Load',
  },
  hardware_diskFailure: {
    id: 'vxweb.Situations.hardware_diskFailure',
    defaultMessage: 'Disk Failure',
  },
  hardware_fanFailure: {
    id: 'vxweb.Situations.hardware_fanFailure',
    defaultMessage: 'Fan Failure',
  },
  hardware_inputLoss: {
    id: 'vxweb.Situations.hardware_inputLoss',
    defaultMessage: 'Input Loss',
  },
  hardware_inputRestored: {
    id: 'vxweb.Situations.hardware_inputRestored',
    defaultMessage: 'Input Restored',
  },
  hardware_linkSpeed: {
    id: 'vxweb.Situations.hardware_linkSpeed',
    defaultMessage: 'Link Speed',
  },
  hardware_memoryLoad: {
    id: 'vxweb.Situations.hardware_memoryLoad',
    defaultMessage: 'Memory Load',
  },
  hardware_networkVolumeFull: {
    id: 'vxweb.Situations.hardware_networkVolumeFull',
    defaultMessage: 'Network Volume Full',
  },
  hardware_networkVolumeOffline: {
    id: 'vxweb.Situations.hardware_networkVolumeOffline',
    defaultMessage: 'Network Volume Offline',
  },
  hardware_networkVolumeOnline: {
    id: 'vxweb.Situations.hardware_networkVolumeOnline',
    defaultMessage: 'Network Volume Online',
  },
  hardware_packetLoss: {
    id: 'vxweb.Situations.hardware_packetLoss',
    defaultMessage: 'Packet Loss',
  },
  hardware_psFailure: {
    id: 'vxweb.Situations.hardware_psFailure',
    defaultMessage: 'Ps Failure',
  },
  hardware_temperature: {
    id: 'vxweb.Situations.hardware_temperature',
    defaultMessage: 'Temperature',
  },
  hardware_upsLow: {
    id: 'vxweb.Situations.hardware_upsLow',
    defaultMessage: 'Ups Low',
  },
  hardware_volumeFull: {
    id: 'vxweb.Situations.hardware_volumeFull',
    defaultMessage: 'Volume Full',
  },
  hardware_volumeOffline: {
    id: 'vxweb.Situations.hardware_volumeOffline',
    defaultMessage: 'Volume Offline',
  },
  hardware_volumeOnline: {
    id: 'vxweb.Situations.hardware_volumeOnline',
    defaultMessage: 'Volume Online',
  },
  system_alarmActive: {
    id: 'vxweb.Situations.system_alarmActive',
    defaultMessage: 'Alarm Active',
  },
  system_alarmInactive: {
    id: 'vxweb.Situations.system_alarmInactive',
    defaultMessage: 'Alarm Inactive',
  },
  system_authenticationFailure: {
    id: 'vxweb.Situations.system_authenticationFailure',
    defaultMessage: 'Authentication Failure',
  },
  system_authorizationFailure: {
    id: 'vxweb.Situations.system_authorizationFailure',
    defaultMessage: 'Authorization Failure',
  },
  system_bookmarkAdded: {
    id: 'vxweb.Situations.system_bookmarkAdded',
    defaultMessage: 'Bookmark Added',
  },
  system_bookmarkLockEnabled: {
    id: 'vxweb.Situations.system_bookmarkLockEnabled',
    defaultMessage: 'Bookmark Lock Enabled',
  },
  system_bookmarkLockModified: {
    id: 'vxweb.Situations.system_bookmarkLockModified',
    defaultMessage: 'Bookmark Lock Modified',
  },
  system_bookmarkLockDisabled: {
    id: 'vxweb.Situations.system_bookmarkLockDisabled',
    defaultMessage: 'Bookmark Lock Disabled',
  },
  system_bookmarkModified: {
    id: 'vxweb.Situations.system_bookmarkModified',
    defaultMessage: 'Bookmark Modified',
  },
  system_bookmarkRemoved: {
    id: 'vxweb.Situations.system_bookmarkRemoved',
    defaultMessage: 'Bookmark Removed',
  },
  system_clientPush: {
    id: 'vxweb.Situations.system_clientPush',
    defaultMessage: 'Client Push',
  },
  system_clientPushAck: {
    id: 'vxweb.Situations.system_clientPushAck',
    defaultMessage: 'Client Push Ack',
  },
  system_clipAdded: {
    id: 'vxweb.Situations.system_clipAdded',
    defaultMessage: 'Clip Added',
  },
  system_clipFailed: {
    id: 'vxweb.Situations.system_clipFailed',
    defaultMessage: 'Clip Failed',
  },
  system_dataSourceOffline: {
    id: 'vxweb.Situations.system_dataSourceOffline',
    defaultMessage: 'Data Source Offline',
  },
  system_dataSourceOnline: {
    id: 'vxweb.Situations.system_dataSourceOnline',
    defaultMessage: 'Data Source Online',
  },
  system_deviceOffline: {
    id: 'vxweb.Situations.system_deviceOffline',
    defaultMessage: 'Device Offline',
  },
  system_deviceOnline: {
    id: 'vxweb.Situations.system_deviceOnline',
    defaultMessage: 'Device Online',
  },
  system_deviceStatusInitialized: {
    id: 'vxweb.Situations.system_deviceStatusInitialized',
    defaultMessage: 'Device Status Initialized',
  },
  system_deviceStatusUnauthenticated: {
    id: 'vxweb.Situations.system_deviceStatusUnauthenticated',
    defaultMessage: 'Device Status Unauthenticated',
  },
  system_exportDeleted: {
    id: 'vxweb.Situations.system_exportDeleted',
    defaultMessage: 'Export Deleted',
  },
  system_exportDownloaded: {
    id: 'vxweb.Situations.system_exportDownloaded',
    defaultMessage: 'Export Downloaded',
  },
  system_exportFailure: {
    id: 'vxweb.Situations.system_exportFailure',
    defaultMessage: 'Export Failure',
  },
  system_exportModified: {
    id: 'vxweb.Situations.system_exportModified',
    defaultMessage: 'Export Modified',
  },
  system_exportRestored: {
    id: 'vxweb.Situations.system_exportRestored',
    defaultMessage: 'Export Restored',
  },
  system_exportStarted: {
    id: 'vxweb.Situations.system_exportStarted',
    defaultMessage: 'Export Started',
  },
  system_exportSuccess: {
    id: 'vxweb.Situations.system_exportSuccess',
    defaultMessage: 'Export Success',
  },
  system_exportTrashed: {
    id: 'vxweb.Situations.system_exportTrashed',
    defaultMessage: 'Export Trashed',
  },
  system_failoverCompleted: {
    id: 'vxweb.Situations.system_failoverCompleted',
    defaultMessage: 'Failover Completed',
  },
  system_failoverStarted: {
    id: 'vxweb.Situations.system_failoverStarted',
    defaultMessage: 'Failover Started',
  },
  system_fault: {
    id: 'vxweb.Situations.system_fault',
    defaultMessage: 'Fault',
  },
  system_manualRecordingAdded: {
    id: 'vxweb.Situations.system_manualRecordingAdded',
    defaultMessage: 'Manual Recording Added',
  },
  system_manualRecordingRemoved: {
    id: 'vxweb.Situations.system_manualRecordingRemoved',
    defaultMessage: 'Manual Recording Removed',
  },
  system_memberOffline: {
    id: 'vxweb.Situations.system_memberOffline',
    defaultMessage: 'Member Offline',
  },
  system_memberOnline: {
    id: 'vxweb.Situations.system_memberOnline',
    defaultMessage: 'Member Online',
  },
  system_ptzLock: {
    id: 'vxweb.Situations.system_ptzLock',
    defaultMessage: 'Ptz Lock',
  },
  system_ptzPatternTriggered: {
    id: 'vxweb.Situations.system_ptzPatternTriggered',
    defaultMessage: 'Ptz Pattern Triggered',
  },
  system_ptzPresetTriggered: {
    id: 'vxweb.Situations.system_ptzPresetTriggered',
    defaultMessage: 'Ptz Preset Triggered',
  },
  system_ptzUnlock: {
    id: 'vxweb.Situations.system_ptzUnlock',
    defaultMessage: 'Ptz Unlock',
  },
  system_qlogDownloaded: {
    id: 'vxweb.Situations.system_qlogDownloaded',
    defaultMessage: 'Qlog Downloaded',
  },
  system_qreportDownloaded: {
    id: 'vxweb.Situations.system_qreportDownloaded',
    defaultMessage: 'Qreport Downloaded',
  },
  system_recordingFailureBandwidth: {
    id: 'vxweb.Situations.system_recordingFailureBandwidth',
    defaultMessage: 'Recording Failure Bandwidth',
  },
  system_relayActive: {
    id: 'vxweb.Situations.system_relayActive',
    defaultMessage: 'Relay Active',
  },
  system_relayInactive: {
    id: 'vxweb.Situations.system_relayInactive',
    defaultMessage: 'Relay Inactive',
  },
  system_retentionLow: {
    id: 'vxweb.Situations.system_retentionLow',
    defaultMessage: 'Retention Low',
  },
  system_scriptFailure: {
    id: 'vxweb.Situations.system_scriptFailure',
    defaultMessage: 'Script Failure',
  },
  system_scriptStarted: {
    id: 'vxweb.Situations.system_scriptStarted',
    defaultMessage: 'Script Started',
  },
  system_scriptSuccess: {
    id: 'vxweb.Situations.system_scriptSuccess',
    defaultMessage: 'Script Success',
  },
  system_streamLoss: {
    id: 'vxweb.Situations.system_streamLoss',
    defaultMessage: 'Stream Loss',
  },
  system_streamRestored: {
    id: 'vxweb.Situations.system_streamRestored',
    defaultMessage: 'Stream Restored',
  },
  system_streamViewDenied: {
    id: 'vxweb.Situations.system_streamViewDenied',
    defaultMessage: 'Stream View Denied',
  },
  system_streamViewStarted: {
    id: 'vxweb.Situations.system_streamViewStarted',
    defaultMessage: 'Stream View Started',
  },
  system_streamViewStopped: {
    id: 'vxweb.Situations.system_streamViewStopped',
    defaultMessage: 'Stream View Stopped',
  },
  system_streamViewTimeout: {
    id: 'vxweb.Situations.system_streamViewTimeout',
    defaultMessage: 'Stream View Timeout',
  },
  system_tagAdded: {
    id: 'vxweb.Situations.system_tagAdded',
    defaultMessage: 'Tag Added',
  },
  system_tagLinked: {
    id: 'vxweb.Situations.system_tagLinked',
    defaultMessage: 'Tag Linked',
  },
  system_tagMerged: {
    id: 'vxweb.Situations.system_tagMerged',
    defaultMessage: 'Tag Merged',
  },
  system_tagModified: {
    id: 'vxweb.Situations.system_tagModified',
    defaultMessage: 'Tag Modified',
  },
  system_tagRemoved: {
    id: 'vxweb.Situations.system_tagRemoved',
    defaultMessage: 'Tag Removed',
  },
  system_tagUnlinked: {
    id: 'vxweb.Situations.system_tagUnlinked',
    defaultMessage: 'Tag Unlinked',
  },
})
