import path = require('path')
import child_process = require('child_process')
import fs = require('fs')

function getInfo(cmd, dir) {
  return child_process.execSync(cmd, {
    cwd: path.dirname(dir),
    encoding: 'utf8',
  }).trim()
}
export function writeFileWithHeaderSync(filename, outputText, generatorSource) {
  const branchName = getInfo('git rev-parse --abbrev-ref HEAD', generatorSource)
  const branchSHA1 = getInfo('git rev-parse --short HEAD', generatorSource)
  // Show a standard path format, relative to the serenity root
  const normalizedSource = path.posix.normalize(/(serenity.*)/.exec(generatorSource)[0])

  let header = `/**
 * This file was generated by running this command:
 * ts-node ${path.relative('.', process.argv[1])}
 * on ${(new Date()).toLocaleString()}
 * from ${normalizedSource} (branch ${branchName}, commit ${branchSHA1})
 * (if modified by hand, replace this line with modification description)
 */
`
  fs.writeFileSync(filename, header + outputText)
}
